server:
  port: 8086
spring:
  application:
    name: gateway
  profiles:
      active: dev
zuul:
#zuul默认反向代理eureka中注册的所有的服务,配置 ignored-services 排除不想代理的
  ignored-services: '*'
#  设置全部服务都可以传递cookie
  sensitive-headers:
#  正则方法排除不需要代理的路由(排除路由中含有 provider 的路由)
#  ignored-patterns:
#    - /**/provider/**
#  配置需要zuul反向代理的服务
  routes:
#     aaa:
#       path: /mdc/**
#       serviceId: provider-mdc
#      zuul默认不会将请求的cookie信息传递到后端服务,添加此配置可以讲cookie传递给后端
#      sensitiveHeaders:
   provider-mdc: /mdc/**
   provider-omc: /omc/**
   provider-tpc: /tpc/**
   provider-uac: /uac/**
management:
  security:
    enabled: false
#  prefix: /api
