spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#    连接池相关设置
#   初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
#    配置获取连接等待超时的时间
    max-wait: 60000
#    配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
#    配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
#    打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxpoolpreparedstatementperconnectionsize: 20
#      配置监控统计
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
#    通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.dodoca.provider.uac.pojo
  configuration:
#   驼峰命名
    map-underscore-to-camel-case: true
#    mybatis二级缓存
    cache-enabled: true
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.dodoca.provider.uac.mapper: debug
env:
  dev
